apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing.fullname" . }}-web
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webService.type }}
  ports:
    - port: {{ .Values.webService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing.fullname" . }}-data
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.discoveryPort.port }}
      name: discovery
      targetPort: discovery
      protocol: UDP
      nodePort: {{ .Values.service.discoveryPort.nodePort }}
    - port: {{ .Values.service.udpPort.port }}
      name: udp-data
      targetPort: udp-data
      protocol: UDP
      nodePort: {{ .Values.service.udpPort.nodePort }}
    - port: {{ .Values.service.tcpPort.port }}
      name: tcp-data
      targetPort: tcp-data
      protocol: TCP
      nodePort: {{ .Values.service.tcpPort.nodePort }}
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}