apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing.fullname" . }}-web
  {{- with .Values.webService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webService.type }}
  ports:
    - port: {{ .Values.webService.port }}
      targetPort: http
      protocol: TCP
      name: http
  externalTrafficPolicy: {{ .Values.webService.externalTrafficPolicy }}
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing.fullname" . }}-data
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.discoveryPort.port }}
      name: discovery
      targetPort: discovery
      protocol: UDP
      nodePort: {{ .Values.service.discoveryPort.nodePort }}
    - port: {{ .Values.service.udpPort.port }}
      name: udp-data
      targetPort: udp-data
      protocol: UDP
      nodePort: {{ .Values.service.udpPort.nodePort }}
    - port: {{ .Values.service.tcpPort.port }}
      name: tcp-data
      targetPort: tcp-data
      protocol: TCP
      nodePort: {{ .Values.service.tcpPort.nodePort }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}