apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.secretName }}
type: Opaque
data:
  serverName: {{ .Values.config.serverName | b64enc }}
  adminUsername: {{ .Values.config.adminUsername | b64enc }}
  adminPassword: {{ .Values.config.adminPassword | b64enc }}
  maxRam: {{ .Values.config.maxRam | b64enc }}
---
{{- if .Values.sftpConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sftpConfig.secretName }}
type: Opaque
data:
  sshUsers: {{ printf "%s:%s:1000:1000:data,server" .Values.sftpConfig.username .Values.sftpConfig.password | b64enc }}
{{- end }}