apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
  name: {{ include "project-zomboid-server.fullname" . }}
  labels:
    {{- include "project-zomboid-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalIPs: {{ .Values.service.externalIPs }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 16261
      protocol: UDP
      name: standard
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - port: {{ .Values.service.directPort }}
      targetPort: 16262
      protocol: UDP
      name: direct
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodeDirectPort }}
      {{- end }}
  selector:
    {{- include "project-zomboid-server.selectorLabels" . | nindent 4 }}
---
{{- if .Values.sftpConfig.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.sftpService.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
  name: {{ include "project-zomboid-server.fullname" . }}-sftp
  labels:
    {{- include "project-zomboid-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sftpService.type }}
  externalIPs: {{ .Values.sftpService.externalIPs }}
  ports:
    - port: {{ .Values.sftpService.port }}
      targetPort: 22
      protocol: TCP
      name: ssh
      {{- if eq .Values.sftpService.type "NodePort" }}
      nodePort: {{ .Values.sftpService.nodePort }}
      {{- end }}
  selector:
    app: {{ include "project-zomboid-server.fullname" . }}-sftp
{{- end }}